### ISSUE TITLE
Parent/subnet interface

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#37]
Depends on: #36

## Background
Every functionality of IPC can be decoupled into a set of low-level interactions with the corresponding parent and child blockchain instances. The `parent` and `subnet` interfaces publish all the low-level methods required by the IPC controllers (subnet, checkpoint, and cross-net) to implement their operation. 

For instance, in order to spawn a subnet, IPC deploys a subnet actor in the parent chain, it sends a message to stake some collateral in the IPC gateway of the parent, and it triggers the spawn of a new blockchain instance for the subnet. All of this is handled by the subnet controller and translated into a set of low-level calls to deploy the actor, send a message to the parent, etc. through the blockchain instance interface. Once #36 is implemented we may realize that there is a lot of overlap between the `parent/subnet` interfaces and the `blockchain instance interface` in which case we may merge all functionality into the same interface ([example of low-level interaction with parent and subnet API](https://github.com/filecoin-project/eudico/blob/6b690b27df22644821f4be0ab3fc12c541fa160e/chain/consensus/hierarchical/subnet/submgr/events.go#L108-L130)).

## Goal
We have an interface exposing the low-level operations that an IPC controller requires to interact with the underlying subnet and parent network deployments. 

## Tasks
- [ ] Translate the operation of the main IPC controllers into low-level operations to determine the operations that need to be exposed by all blockchain instances (as mentioned above, we may deem this interface unnecessary ant the controllers may be able to directly attack the latter).
- [ ] Design the interface.
- [ ] Implementation of the interface.

**Comment by adlrocha** [comment]
Being implemented in https://github.com/consensus-shipyard/ipc-agent
